### ISSUE TITLE
Should we add a .gitignore?

### ISSUE THREAD

**Issue by wzhouwzhou** [wzhouwzhou/one-line-wonders#14]
Should we add a gitignore to catch files such as `.DS_Store`? (even though people will be pulling individual "one-line" code files) and what would need to be in it?

**Comment by kannagikazuko** [comment]
I believe that for consistency, just in case, that would be great!

**Comment by Priultimus** [comment]
There's #15 :^)

**Comment by kannagikazuko** [comment]
Merged, thanks!
