### ISSUE TITLE
String Reversal

### ISSUE THREAD

**Issue by wzhouwzhou** [wzhouwzhou/one-line-wonders#177]
### Originally a javascript "code golf" type question

Create a one-line arrow function that, given a string, reverses it
reverse('Hello') -> 'olleH'

  • Under 75 characters
  • Does not use any .reverse .reduce .substring, .substr, .split, any loops, or list/array work
  • Does not use any bit shifts, "mathy" operators `+ - * / =` or conditional operator
Hint: Recursion appreciated

#### My solution is [here](https://github.com/kannagikazuko/one-line-wonders/blob/master/javascript/reverse-string-wzhouwzhou.js)
**Can this be done in other languages? Do other people have different solutions in javascript?**

**Comment by HeckerBirb** [comment]
Isn't slicing also "list/array work"?

**Comment by wzhouwzhou** [comment]
\<String\>#slice doesn't involve \<Array\> objects, it works like substring except negative indices are allowed
https://chromium.googlesource.com/v8/v8/+/4.3.49/src/string.js?autodive=0%2F%2F#551

**Comment by ganes1410** [comment]
@wzhouwzhou That is already done by someone

**Comment by wzhouwzhou** [comment]
@ganes1410
>Can this be done in other languages? Do other people have different solutions in javascript?

**Comment by ganes1410** [comment]
@wzhouwzhou  sorry

**Comment by wzhouwzhou** [comment]
No worries, just keeping the repo/problem available to the open-source community at large
