### ISSUE TITLE
Add docstrings

### ISSUE THREAD

**Issue by s-ankur** [wzhouwzhou/one-line-wonders#236]
In a lot of these one liners, it is somewhat unclear how we should run these programs. While the respective pull requests have all the documentation we need, it doesnt appear in the actual programs. I think we should add docstrings or comments to all the programs so that it will be clear how one should run them.

**Comment by wzhouwzhou** [comment]
I think that’s a good idea, at the very least it would be nice for people to include a link to the PR with instructions 
I might make some sort of checklist in the pull request template for this.
Meanwhile, if people want to start opening issues tagging program authors to do so (as opposed to editing someone else's program), that would be nice. Some programs in our repo have great comments as well as tests while others don't, and I think consistency would be nice

**Comment by Zylatis** [comment]
This may be overcomplicating things, ironically given the purpose of the repo, but would it be helpful to have class or function templates built for each submission? I'm imagining something similar to say Leetcodes 'solution class' where the user defines one method and all the other stuff is dealt with. Class might be overkill, probably a simple fn is sufficient for most. We could then make a ReadTheDocs for this =D

**Comment by wzhouwzhou** [comment]
@Zylatis That sounds cool, but I'm not too sure how we would implement something like that in an easy and consistent way for anyone to contribute in any language, even if they've never used GitHub before. Do you already have something in mind we can on-board into the repo somehow?
