### ISSUE TITLE
More open licence?

### ISSUE THREAD

**Issue by omicron321** [wzhouwzhou/one-line-wonders#243]
Imho that kind of collection could benefit from more permissive license like MIT-like licenses.

**Comment by wzhouwzhou** [comment]
Thank you for your concern regarding licensing. Most of the code in this repository should not be used as-is in production code. GNU restricts redistribution of closed source versions. This repository was inspired by a shared love for one-line programs that target specific language semantics. It is an ideal repository for both novice and experienced programmers and, in conjunction with Hacktoberfest, contributes to the open source community at large. GNU was chosen in an effort to preserve this fundamental value that brings together many people over a single idea.
https://choosealicense.com/ may be a useful resource to see that GNU does allow you to do many things with the code.
Thanks for understanding.
