### ISSUE TITLE
Add links to references in PR template

### ISSUE THREAD

**Issue by jackkav** [wzhouwzhou/one-line-wonders#337]
I think it would be useful to add reference to the one liner PRs to give more context for the reviewer. Using `[`title`](`url`)`

Examples of prior work, reference or inspiration include:

- example input and output
- use case, or problem it solves
- similar solution in another language

**Comment by wzhouwzhou** [comment]
Related to #236, it'd be great for people to include those instructions as comments within the program files themselves, and any pull requests that do that would count as well.
